export const GAME_CONFIG = {
    "Genshin Impact": {
        current: {
            version: 6.4,
            version_start: "2026-02-25",
            version_duration: 42,
            characters: ['Varka', null],
            version_duration_confirmation: true,
        },
        next: {
            version: 6.5,
            future_livestream_version: 6.6,
            version_duration: 42,
            characters: ['Linnea', null],
            version_duration_confirmation: true,
        },
        maintenance_start: [22, 0], // Hour, Min
        maintenance_duration: [5, 0], // Hour, Min
        livestream_hour: [12, 0], // 05:00 in certain livestreams
        livestream_prediction: true,
        trailer_distance: 1,
        servers: {
            "America": { uid_prefix: 6, daily_reset: 9 },
            "Europe": { uid_prefix: 7, daily_reset: 3 },
            "Asia": { uid_prefix: 8, daily_reset: 20 },
            "TW/HK/MO": { uid_prefix: 9, daily_reset: 20 },
        },
        second_phase_hours: { "America": 17, "Europe": 11, "Asia": 4, "TW/HK/MO": 4 },
        abbr: "GI",
        process: "GenshinImpact.exe",
        color: "#C8922A",
    },
    "Honkai: Star Rail": {
        current: {
            version: 4.1,
            version_start: "2026-03-25",
            version_duration: 28,
            characters: ['Ashveil', null],
            version_duration_confirmation: true,
        },
        next: {
            version: 4.2,
            future_livestream_version: 4.3,
            version_duration: 42,
            characters: ['Silver Wolf LV.999', "Evanescia"],
            version_duration_confirmation: true,
        },
        maintenance_start: [22, 0],
        maintenance_duration: [5, 0],
        livestream_hour: [11, 30],
        livestream_prediction: true,
        trailer_distance: 3,
        weekly_anchors: {
            "Currency Wars": "2026-02-16T00:00:00Z",
            "Divergent Universe": "2026-02-09T00:00:00Z"
        },
        endgame_anchors: {
            "Memory of Chaos": "2026-01-19T00:00:00Z",
            "Pure Fiction": "2026-02-16T00:00:00Z",
            "Apocalyptic Shadow": "2026-02-02T00:00:00Z"
        },
        servers: {
            "America": { uid_prefix: 6, daily_reset: 9 },
            "Europe": { uid_prefix: 7, daily_reset: 3 },
            "Asia": { uid_prefix: 8, daily_reset: 20 },
            "TW/HK/MO": { uid_prefix: 9, daily_reset: 20 },
        },
        second_phase_hours: { "America": 17, "Europe": 11, "Asia": 4, "TW/HK/MO": 4 },
        abbr: "HSR",
        process: "StarRail.exe",
        color: "#4A9ECD",
    },
    "Zenless Zone Zero": {
        current: {
            version: 2.7,
            version_start: "2026-03-24",
            version_duration: 43,
            characters: ['Nangong Yu', 'Cissia'],
            version_duration_confirmation: true,
        },
        next: {
            version: 2.8,
            future_livestream_version: 2.8,
            version_duration: 42,
            characters: ['Promeia', null],
            version_duration_confirmation: false,
        },
        maintenance_start: [22, 0],
        maintenance_duration: [5, 0],
        livestream_hour: [11, 30],
        livestream_prediction: true,
        trailer_distance: 4,
        endgame_anchors: {
            "Shiyu Defense": "2026-02-20T00:00:00Z",
            "Deadly Assault": "2026-02-13T00:00:00Z",
            "Battle Trial": "2026-03-24T00:00:00Z",
            "Threshold Simulation": "2026-02-06T00:00:00Z"
        },
        servers: {
            "America": { uid_prefix: 6, daily_reset: 9 },
            "Europe": { uid_prefix: 7, daily_reset: 3 },
            "Asia": { uid_prefix: 8, daily_reset: 20 },
            "TW/HK/MO": { uid_prefix: 9, daily_reset: 20 },
        },
        second_phase_hours: { "America": 17, "Europe": 11, "Asia": 4, "TW/HK/MO": 4 },
        abbr: "ZZZ",
        process: "ZenlessZoneZero.exe",
        color: "#C9D400"
    },
    "Arknights Endfield": {
        current: {
            version: 1.1,
            version_start: "2026-03-12",
            version_duration: 36,
            characters: ['Tangtang', 'Rossi'],
            version_duration_confirmation: true,
        },
        next: {
            version: 1.2,
            future_livestream_version: 1.3,
            version_duration: 42,
            characters: [null, null],
            version_duration_confirmation: false,
        },
        livestream_prediction: false,
        maintenance_start: [22, 0],
        maintenance_duration: [6, 0],
        livestream_hour: [11, 30],
        livestream_date: "2026-04-11",
        trailer_distance: 1,
        servers: {
            "Americas/Europe": { uid_prefix: 6, daily_reset: 9, second_phase: 17 },
            "Asia": { uid_prefix: 4, daily_reset: 20, second_phase: 4 },
        },
        second_phase_hours: { "America": 17, "Europe": 17, "Asia": 4 },
        abbr: "AK",
        process: "Endfield.exe",
        color: "#3ABFB0",
    },
    "Infinity Nikki": {
        current: {
            version: 2.4,
            version_start: "2026-03-26",
            version_duration: 29,
            characters: [null, null],
            version_duration_confirmation: true,
        },
        next: {
            version: 2.5,
            future_livestream_version: 2.6,
            version_duration: 25,
            characters: [null, null],
            version_duration_confirmation: false,
        },
        livestream_prediction: false,
        maintenance_start: [19, 50],
        maintenance_duration: [7, 10],
        livestream_hour: [12, 0],
        livestream_date: "2026-04-19",
        trailer_distance: 1,
        servers: {
            "America": { uid_prefix: 6, daily_reset: 11 },
            "Europe": { uid_prefix: 2, daily_reset: 2 },
            "Asia": { uid_prefix: 4, daily_reset: 20 },
        },
        second_phase_hours: { "America": 3, "Europe": 3, "Asia": 3 },
        second_phase_offset: 1,
        abbr: "IN",
        process: "X6Game-Win64-Shipping.exe",
        color: "#E8729A",
    }
}